export let barangayNames = [
  "Barangay 121",
  "Barangay 122",
  "Barangay 123",
  "Barangay 124",
  "Barangay 125",
  "Barangay 126",
  "Barangay 127",
  "Barangay 128",
  "Barangay 129",
  "Barangay 130",
  "Barangay 131",
  "Barangay 132",
  "Barangay 133",
  "Barangay 134",
  "Barangay 135",
  "Barangay 136",
  "Barangay 137",
  "Barangay 138",
  "Barangay 139",
  "Barangay 140",
  "Barangay 141",
  "Barangay 142",
  "Barangay 143",
  "Barangay 144",
  "Barangay 145",
  "Barangay 146",
  "Barangay 147",
  "Barangay 148",
  "Barangay 149",
  "Barangay 150",
  "Barangay 151",
  "Barangay 152",
  "Barangay 153",
  "Barangay 154",
  "Barangay 155",
  "Barangay 156",
  "Barangay 157",
  "Barangay 158",
  "Barangay 159",
  "Barangay 160",
  "Barangay 161",
  "Barangay 162",
  "Barangay 163",
  "Barangay 164",
  "Barangay 165",
  "Barangay 166",
  "Barangay 167",
  "Barangay 168",
  "Barangay 169",
  "Barangay 170",
  "Barangay 171",
  "Barangay 172",
  "Barangay 173",
  "Barangay 174",
  "Barangay 175",
  "Barangay 176",
  "Barangay 177",
  "Barangay 178",
  "Barangay 179",
  "Barangay 180",
  "Barangay 181",
  "Barangay 182",
  "Barangay 183",
  "Barangay 184",
  "Barangay 185",
  "Barangay 186",
  "Barangay 187",
  "Barangay 188",
];

export let barangayItemsData = [
  {
    name: "Amoxicillin 500mg Capsule",
    unit: "100's/box",
    stock: 0,
    description: "Antibiotic",
  },
  {
    name: "Cefalexicin 500mg Capsule",
    unit: "100's/box",
    stock: 0,
    description: "Antibiotic",
  },
  {
    name: "Clopidogrel 75mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Antiplatelet",
  },
  {
    name: "Celecoxib 200mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Anti-inflammatory",
  },
  {
    name: "Cetirizine 10mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Antihistamine",
  },
  {
    name: "Lagundi 300mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Herbal Supplement",
  },
  {
    name: "Losartan 50mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Antihypertensive",
  },
  {
    name: "Mefenamic Acid 500mg Capsule",
    unit: "100's/box",
    stock: 0,
    description: "Analgesic",
  },
  {
    name: "Metformin 500mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Antidiabetic",
  },
  {
    name: "Metoprolol 50mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Beta Blocker",
  },
  {
    name: "Multivitamins Capsule",
    unit: "100's/box",
    stock: 0,
    description: "Multivitamin",
  },
  {
    name: "Omeprazole 20mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Proton Pump Inhibitor",
  },
  {
    name: "Oral Rehydration Salt Sachet",
    unit: "25's/box",
    stock: 0,
    description: "Electrolyte Replacement",
  },
  {
    name: "Paracetamol 500mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Analgesic",
  },
  {
    name: "Salbutamol 2mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Bronchodilator",
  },
  {
    name: "Salbutamol 2mg Nebule",
    unit: "30's/box",
    stock: 0,
    description: "Bronchodilator",
  },
  {
    name: "Vitamin B1, B6, B12 Tablets",
    unit: "100's/box",
    stock: 0,
    description: "Vitamin Supplement",
  },
  {
    name: "Amoxicillin 250mg/5ml Suspension",
    unit: "60ml 144's/box",
    stock: 0,
    description: "Antibiotic",
  },
  {
    name: "Cetirizine 5mg/ml Syrup",
    unit: "60ml 144's/box",
    stock: 0,
    description: "Antihistamine",
  },
  {
    name: "Lagundi 300mg/5ml Syrup",
    unit: "60ml 144's/box",
    stock: 0,
    description: "Herbal Supplement",
  },
  {
    name: "Multivitamins Syrup",
    unit: "60ml 144's/box",
    stock: 0,
    description: "Multivitamin",
  },
  {
    name: "Paracetamol 250mg/5ml Syrup",
    unit: "60ml 144's/box",
    stock: 0,
    description: "Analgesic",
  },
  {
    name: "Salbutamol 2mg Syrup",
    unit: "60ml 144's/box",
    stock: 0,
    description: "Bronchodilator",
  },
  {
    name: "Amoxicillin 100mg/ml Drops",
    unit: "10ml 144's/box",
    stock: 0,
    description: "Antibiotic",
  },
  {
    name: "Cetirizine 2.5mg/ml Drops",
    unit: "10ml 144's/box",
    stock: 0,
    description: "Antihistamine",
  },
  {
    name: "Multivitamins Drops",
    unit: "15ml 144's/box",
    stock: 0,
    description: "Multivitamin",
  },
  {
    name: "Paracetamol 100mg/ml Drops",
    unit: "10ml 144's/box",
    stock: 0,
    description: "Analgesic",
  },
];
