export interface TBarangaySeed {
  barangayName: string;
  zip: number;
  district: string;
}

export const barangayNames: TBarangaySeed[] = [
  { barangayName: 'Barangay 1', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 2', zip: 1400,district: "District 1" },
  { barangayName: 'Barangay 3', zip: 1400,district: "District 1" },
  { barangayName: 'Barangay 4', zip: 1400,district: "District 1" },
  { barangayName: 'Barangay 5', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 6', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 7', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 8', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 9', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 10', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 11', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 12', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 13', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 14', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 15', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 16', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 17', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 18', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 19', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 20', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 21', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 22', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 23', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 24', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 25', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 26', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 27', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 28', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 29', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 30', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 31', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 32', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 33', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 34', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 35', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 36', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 37', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 38', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 39', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 40', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 41', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 42', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 43', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 44', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 45', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 46', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 47', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 48', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 49', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 50', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 51', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 52', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 53', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 54', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 55', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 56', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 57', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 58', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 59', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 60', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 61', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 62', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 63', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 64', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 65', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 66', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 67', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 68', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 69', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 70', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 71', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 72', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 73', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 74', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 75', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 76', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 77', zip: 1400, district:"District 1" },
  { barangayName: 'Barangay 78', zip: 1400, district:"District 1" },
  { barangayName: 'Barangay 79', zip: 1400, district:"District 1" },
  { barangayName: 'Barangay 80', zip: 1400, district:"District 1" },
  { barangayName: 'Barangay 81', zip: 1400, district:"District 1" },
  { barangayName: 'Barangay 82', zip: 1400, district:"District 1" },
  { barangayName: 'Barangay 83', zip: 1400, district:"District 1" },
  { barangayName: 'Barangay 84', zip: 1400, district:"District 1" },
  { barangayName: 'Barangay 85', zip: 1400, district:"District 1" },
  { barangayName: 'Barangay 86', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 87', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 88', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 89', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 90', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 91', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 92', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 93', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 94', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 95', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 96', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 97', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 98', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 99', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 100', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 101', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 102', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 103', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 104', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 105', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 106', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 107', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 108', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 109', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 110', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 111', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 112', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 113', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 114', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 115', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 116', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 117', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 118', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 119', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 120', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 121', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 122', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 123', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 124', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 125', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 126', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 127', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 128', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 129', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 130', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 131', zip: 1400, district: "District 2" },
  { barangayName: 'Barangay 132', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 133', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 134', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 135', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 136', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 137', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 138', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 139', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 140', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 141', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 142', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 143', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 144', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 145', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 146', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 147', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 148', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 149', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 150', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 151', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 152', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 153', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 154', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 155', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 156', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 157', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 158', zip: 1400, district: "District 1" },
  { barangayName: 'Barangay 159', zip: 1400, district: "District 1" },
{ barangayName: 'Barangay 160', zip: 1400, district: "District 1" },
{ barangayName: 'Barangay 161', zip: 1400, district: "District 1" },
{ barangayName: 'Barangay 162', zip: 1400, district: "District 1" },
{ barangayName: 'Barangay 163', zip: 1400, district: "District 1" },
{ barangayName: 'Barangay 164', zip: 1400, district: "District 1" },
{ barangayName: 'Barangay 165', zip: 1400, district: "District 1" },
{ barangayName: 'Barangay 166', zip: 1420, district: "District 1" },
{ barangayName: 'Barangay 167', zip: 1400, district: "District 1" },
{ barangayName: 'Barangay 168', zip: 1400, district: "District 1" },
{ barangayName: 'Barangay 169', zip: 1400, district: "District 1" },
{ barangayName: 'Barangay 170', zip: 1400, district: "District 1" },
{ barangayName: 'Barangay 171', zip: 1421, district: "District 1" },
{ barangayName: 'Barangay 172', zip: 1400, district: "District 1" },
{ barangayName: 'Barangay 173', zip: 1400, district: "District 1" },
{ barangayName: 'Barangay 174', zip: 1422, district: "District 1" },
{ barangayName: 'Barangay 175', zip: 1422, district: "District 1" },
{ barangayName: 'Barangay 176', zip: 1428, district: "District 1" },
{ barangayName: 'Barangay 177', zip: 1422, district: "District 1" },
{ barangayName: 'Barangay 178', zip: 1422, district: "District 3" },
{ barangayName: 'Barangay 179', zip: 1425, district: "District 3" },
{ barangayName: 'Barangay 180', zip: 1400, district: "District 3" },
{ barangayName: 'Barangay 181', zip: 1400, district: "District 3" },
{ barangayName: 'Barangay 182', zip: 1400, district: "District 3" },
{ barangayName: 'Barangay 183', zip: 1400, district: "District 3" },
{ barangayName: 'Barangay 184', zip: 1400, district: "District 3" },
{ barangayName: 'Barangay 185', zip: 1400, district: "District 3" },
{ barangayName: 'Barangay 186', zip: 1427, district: "District 3" },
{ barangayName: 'Barangay 187', zip: 1400, district: "District 3" },
{ barangayName: 'Barangay 188', zip: 1400, district: "District 3" },
];

// export let barangayNames = [
//   "Barangay 1",
//   "Barangay 2",
//   "Barangay 3",
//   "Barangay 4",
//   "Barangay 5",
//   "Barangay 6",
//   "Barangay 7",
//   "Barangay 8",
//   "Barangay 9",
//   "Barangay 10",
//   "Barangay 11",
//   "Barangay 12",
//   "Barangay 13",
//   "Barangay 14",
//   "Barangay 15",
//   "Barangay 16",
//   "Barangay 17",
//   "Barangay 18",
//   "Barangay 19",
//   "Barangay 20",
//   "Barangay 21",
//   "Barangay 22",
//   "Barangay 23",
//   "Barangay 24",
//   "Barangay 25",
//   "Barangay 26",
//   "Barangay 27",
//   "Barangay 28",
//   "Barangay 29",
//   "Barangay 30",
//   "Barangay 31",
//   "Barangay 32",
//   "Barangay 33",
//   "Barangay 34",
//   "Barangay 35",
//   "Barangay 36",
//   "Barangay 37",
//   "Barangay 38",
//   "Barangay 39",
//   "Barangay 40",
//   "Barangay 41",
//   "Barangay 42",
//   "Barangay 43",
//   "Barangay 44",
//   "Barangay 45",
//   "Barangay 46",
//   "Barangay 47",
//   "Barangay 48",
//   "Barangay 49",
//   "Barangay 50",
//   "Barangay 51",
//   "Barangay 52",
//   "Barangay 53",
//   "Barangay 54",
//   "Barangay 55",
//   "Barangay 56",
//   "Barangay 57",
//   "Barangay 58",
//   "Barangay 59",
//   "Barangay 60",
//   "Barangay 61",
//   "Barangay 62",
//   "Barangay 63",
//   "Barangay 64",
//   "Barangay 65",
//   "Barangay 66",
//   "Barangay 67",
//   "Barangay 68",
//   "Barangay 69",
//   "Barangay 70",
//   "Barangay 71",
//   "Barangay 72",
//   "Barangay 73",
//   "Barangay 74",
//   "Barangay 75",
//   "Barangay 76",
//   "Barangay 77",
//   "Barangay 78",
//   "Barangay 79",
//   "Barangay 80",
//   "Barangay 81",
//   "Barangay 82",
//   "Barangay 83",
//   "Barangay 84",
//   "Barangay 85",
//   "Barangay 86",
//   "Barangay 87",
//   "Barangay 88",
//   "Barangay 89",
//   "Barangay 90",
//   "Barangay 91",
//   "Barangay 92",
//   "Barangay 93",
//   "Barangay 94",
//   "Barangay 95",
//   "Barangay 96",
//   "Barangay 97",
//   "Barangay 98",
//   "Barangay 99",
//   "Barangay 100",
//   "Barangay 101",
//   "Barangay 102",
//   "Barangay 103",
//   "Barangay 104",
//   "Barangay 105",
//   "Barangay 106",
//   "Barangay 107",
//   "Barangay 108",
//   "Barangay 109",
//   "Barangay 110",
//   "Barangay 111",
//   "Barangay 112",
//   "Barangay 113",
//   "Barangay 114",
//   "Barangay 115",
//   "Barangay 116",
//   "Barangay 117",
//   "Barangay 118",
//   "Barangay 119",
//   "Barangay 120",
//   "Barangay 121",
//   "Barangay 122",
//   "Barangay 123",
//   "Barangay 124",
//   "Barangay 125",
//   "Barangay 126",
//   "Barangay 127",
//   "Barangay 128",
//   "Barangay 129",
//   "Barangay 130",
//   "Barangay 131",
//   "Barangay 132",
//   "Barangay 133",
//   "Barangay 134",
//   "Barangay 135",
//   "Barangay 136",
//   "Barangay 137",
//   "Barangay 138",
//   "Barangay 139",
//   "Barangay 140",
//   "Barangay 141",
//   "Barangay 142",
//   "Barangay 143",
//   "Barangay 144",
//   "Barangay 145",
//   "Barangay 146",
//   "Barangay 147",
//   "Barangay 148",
//   "Barangay 149",
//   "Barangay 150",
//   "Barangay 151",
//   "Barangay 152",
//   "Barangay 153",
//   "Barangay 154",
//   "Barangay 155",
//   "Barangay 156",
//   "Barangay 157",
//   "Barangay 158",
//   "Barangay 159",
//   "Barangay 160",
//   "Barangay 161",
//   "Barangay 162",
//   "Barangay 163",
//   "Barangay 164",
//   "Barangay 165",
//   "Barangay 166",
//   "Barangay 167",
//   "Barangay 168",
//   "Barangay 169",
//   "Barangay 170",
//   "Barangay 171",
//   "Barangay 172",
//   "Barangay 173",
//   "Barangay 174",
//   "Barangay 175",
//   "Barangay 176",
//   "Barangay 177",
//   "Barangay 178",
//   "Barangay 179",
//   "Barangay 180",
//   "Barangay 181",
//   "Barangay 182",
//   "Barangay 183",
//   "Barangay 184",
//   "Barangay 185",
//   "Barangay 186",
//   "Barangay 187",
//   "Barangay 188",
// ];

export let barangayItemsData = [
  {
    name: "Amoxicillin Capsule",
    unit: "box",
    stock: 99,
    dosage: "500mg",
    description: "Antibiotic",
  },
  {
    name: "Cefalexicin Capsule",
    unit: "box",
    stock: 99,
    dosage: "500mg",
    description: "Antibiotic",
  },
  {
    name: "Clopidogrel  Tablet",
    unit: "box",
    stock: 99,
    dosage: "75mg",
    description: "Antiplatelet",
  },
  {
    name: "Celecoxib Tablet",
    unit: "box",
    stock: 99,
    dosage: "200mg",
    description: "Anti-inflammatory",
  },
  {
    name: "Cetirizine Tablet",
    unit: "box",
    stock: 99,
    dosage: "10mg",
    description: "Antihistamine",
  },
  {
    name: "Lagundi  Tablet",
    unit: "box",
    stock: 99,
    dosage: "300mg",
    description: "Herbal Supplement",
  },
  {
    name: "Losartan  Tablet",
    unit: "box",
    stock: 99,
    dosage: "50mg",
    description: "Antihypertensive",
  },
  {
    name: "Mefenamic Acid  Capsule",
    unit: "box",
    stock: 0,
    dosage: "500mg",
    description: "Analgesic",
  },
  {
    name: "Metformin Tablet",
    unit: "box",
    stock: 99,
    dosage: "500mg",
    description: "Antidiabetic",
  },
  {
    name: "Metoprolol Tablet",
    unit: "box",
    stock: 99,
    dosage: "50mg",
    description: "Beta Blocker",
  },
  {
    name: "Multivitamins Capsule",
    unit: "box",
    stock: 99,
    dosage: "500mg",
    description: "Multivitamin",
  },
  {
    name: "Omeprazole  Tablet",
    unit: "box",
    stock: 99,
    dosage: "20mg",
    description: "Proton Pump Inhibitor",
  },
  {
    name: "Oral Rehydration Salt Sachet",
    unit: "box",
    stock: 99,
    dosage: "20mg",
    description: "Electrolyte Replacement",
  },
  {
    name: "Paracetamol Tablet",
    unit: "box",
    stock: 99,
    dosage: "500mg",
    description: "Analgesic",
  },
  {
    name: "Salbutamol Tablet",
    unit: "box",
    stock: 99,
    dosage: "2mg",
    description: "Bronchodilator",
  },
  {
    name: "Salbutamol Nebule",
    unit: "box",
    stock: 99,
    dosage: "2mg",
    description: "Bronchodilator",
  },
  {
    name: "Vitamin B1, B6, B12 Tablets",
    unit: "box",
    stock: 99,
    dosage: "500mg",
    description: "Vitamin Supplement",
  },
  {
    name: "Amoxicillin Suspension",
    unit: "box",
    stock: 99,
    dosage: "250mg/5ml",
    description: "Antibiotic",
  },
  {
    name: "Cetirizine Syrup",
    unit: "box",
    stock: 99,
    dosage: "5mg/5ml",
    description: "Antihistamine",
  },
  {
    name: "Lagundi Syrup",
    unit: "box",
    stock: 99,
    dosage: "300mg/5ml",
    description: "Herbal Supplement",
  },
  {
    name: "Multivitamins Syrup",
    unit: "box",
    stock: 99,
    dosage: "60ml",
    description: "Multivitamin",
  },
  {
    name: "Paracetamol Syrup",
    unit: "box",
    stock: 99,
    dosage: "120mg/5ml",
    description: "Analgesic",
  },
  {
    name: "Salbutamol Syrup",
    unit: "box",
    stock: 99,
    dosage: "2mg",
    description: "Bronchodilator",
  },
  {
    name: "Amoxicillin Drops",
    unit: "box",
    stock: 99,
    dosage: "100mg/ml",
    description: "Antibiotic",
  },
  {
    name: "Cetirizine  Drops",
    unit: "box",
    stock: 99,
    dosage: "2.5mg/ml",
    description: "Antihistamine",
  },
  {
    name: "Multivitamins Drops",
    unit: "box",
    stock: 99,
    dosage: "15ml",
    description: "Multivitamin",
  },
  {
    name: "Paracetamol Drops",
    unit: "box",
    stock: 99,
    dosage: "100mg/ml",
    description: "Analgesic",
  },
];
