export let barangayNames = [
  "Barangay 1",
  "Barangay 2",
  "Barangay 3",
  "Barangay 4",
  "Barangay 5",
  "Barangay 6",
  "Barangay 7",
  "Barangay 8",
  "Barangay 9",
  "Barangay 10",
  "Barangay 11",
  "Barangay 12",
  "Barangay 13",
  "Barangay 14",
  "Barangay 15",
  "Barangay 16",
  "Barangay 17",
  "Barangay 18",
  "Barangay 19",
  "Barangay 20",
  "Barangay 21",
  "Barangay 22",
  "Barangay 23",
  "Barangay 24",
  "Barangay 25",
  "Barangay 26",
  "Barangay 27",
  "Barangay 28",
  "Barangay 29",
  "Barangay 30",
  "Barangay 31",
  "Barangay 32",
  "Barangay 33",
  "Barangay 34",
  "Barangay 35",
  "Barangay 36",
  "Barangay 37",
  "Barangay 38",
  "Barangay 39",
  "Barangay 40",
  "Barangay 41",
  "Barangay 42",
  "Barangay 43",
  "Barangay 44",
  "Barangay 45",
  "Barangay 46",
  "Barangay 47",
  "Barangay 48",
  "Barangay 49",
  "Barangay 50",
  "Barangay 51",
  "Barangay 52",
  "Barangay 53",
  "Barangay 54",
  "Barangay 55",
  "Barangay 56",
  "Barangay 57",
  "Barangay 58",
  "Barangay 59",
  "Barangay 60",
  "Barangay 61",
  "Barangay 62",
  "Barangay 63",
  "Barangay 64",
  "Barangay 65",
  "Barangay 66",
  "Barangay 67",
  "Barangay 68",
  "Barangay 69",
  "Barangay 70",
  "Barangay 71",
  "Barangay 72",
  "Barangay 73",
  "Barangay 74",
  "Barangay 75",
  "Barangay 76",
  "Barangay 77",
  "Barangay 78",
  "Barangay 79",
  "Barangay 80",
  "Barangay 81",
  "Barangay 82",
  "Barangay 83",
  "Barangay 84",
  "Barangay 85",
  "Barangay 86",
  "Barangay 87",
  "Barangay 88",
  "Barangay 89",
  "Barangay 90",
  "Barangay 91",
  "Barangay 92",
  "Barangay 93",
  "Barangay 94",
  "Barangay 95",
  "Barangay 96",
  "Barangay 97",
  "Barangay 98",
  "Barangay 99",
  "Barangay 100",
  "Barangay 101",
  "Barangay 102",
  "Barangay 103",
  "Barangay 104",
  "Barangay 105",
  "Barangay 106",
  "Barangay 107",
  "Barangay 108",
  "Barangay 109",
  "Barangay 110",
  "Barangay 111",
  "Barangay 112",
  "Barangay 113",
  "Barangay 114",
  "Barangay 115",
  "Barangay 116",
  "Barangay 117",
  "Barangay 118",
  "Barangay 119",
  "Barangay 120",
  "Barangay 121",
  "Barangay 122",
  "Barangay 123",
  "Barangay 124",
  "Barangay 125",
  "Barangay 126",
  "Barangay 127",
  "Barangay 128",
  "Barangay 129",
  "Barangay 130",
  "Barangay 131",
  "Barangay 132",
  "Barangay 133",
  "Barangay 134",
  "Barangay 135",
  "Barangay 136",
  "Barangay 137",
  "Barangay 138",
  "Barangay 139",
  "Barangay 140",
  "Barangay 141",
  "Barangay 142",
  "Barangay 143",
  "Barangay 144",
  "Barangay 145",
  "Barangay 146",
  "Barangay 147",
  "Barangay 148",
  "Barangay 149",
  "Barangay 150",
  "Barangay 151",
  "Barangay 152",
  "Barangay 153",
  "Barangay 154",
  "Barangay 155",
  "Barangay 156",
  "Barangay 157",
  "Barangay 158",
  "Barangay 159",
  "Barangay 160",
  "Barangay 161",
  "Barangay 162",
  "Barangay 163",
  "Barangay 164",
  "Barangay 165",
  "Barangay 166",
  "Barangay 167",
  "Barangay 168",
  "Barangay 169",
  "Barangay 170",
  "Barangay 171",
  "Barangay 172",
  "Barangay 173",
  "Barangay 174",
  "Barangay 175",
  "Barangay 176",
  "Barangay 177",
  "Barangay 178",
  "Barangay 179",
  "Barangay 180",
  "Barangay 181",
  "Barangay 182",
  "Barangay 183",
  "Barangay 184",
  "Barangay 185",
  "Barangay 186",
  "Barangay 187",
  "Barangay 188",
];

export let barangayItemsData = [
  {
    name: "Amoxicillin 500mg Capsule",
    unit: "100's/box",
    stock: 0,
    description: "Antibiotic",
  },
  {
    name: "Cefalexicin 500mg Capsule",
    unit: "100's/box",
    stock: 0,
    description: "Antibiotic",
  },
  {
    name: "Clopidogrel 75mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Antiplatelet",
  },
  {
    name: "Celecoxib 200mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Anti-inflammatory",
  },
  {
    name: "Cetirizine 10mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Antihistamine",
  },
  {
    name: "Lagundi 300mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Herbal Supplement",
  },
  {
    name: "Losartan 50mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Antihypertensive",
  },
  {
    name: "Mefenamic Acid 500mg Capsule",
    unit: "100's/box",
    stock: 0,
    description: "Analgesic",
  },
  {
    name: "Metformin 500mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Antidiabetic",
  },
  {
    name: "Metoprolol 50mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Beta Blocker",
  },
  {
    name: "Multivitamins Capsule",
    unit: "100's/box",
    stock: 0,
    description: "Multivitamin",
  },
  {
    name: "Omeprazole 20mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Proton Pump Inhibitor",
  },
  {
    name: "Oral Rehydration Salt Sachet",
    unit: "25's/box",
    stock: 0,
    description: "Electrolyte Replacement",
  },
  {
    name: "Paracetamol 500mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Analgesic",
  },
  {
    name: "Salbutamol 2mg Tablet",
    unit: "100's/box",
    stock: 0,
    description: "Bronchodilator",
  },
  {
    name: "Salbutamol 2mg Nebule",
    unit: "30's/box",
    stock: 0,
    description: "Bronchodilator",
  },
  {
    name: "Vitamin B1, B6, B12 Tablets",
    unit: "100's/box",
    stock: 0,
    description: "Vitamin Supplement",
  },
  {
    name: "Amoxicillin 250mg/5ml Suspension",
    unit: "60ml 144's/box",
    stock: 0,
    description: "Antibiotic",
  },
  {
    name: "Cetirizine 5mg/ml Syrup",
    unit: "60ml 144's/box",
    stock: 0,
    description: "Antihistamine",
  },
  {
    name: "Lagundi 300mg/5ml Syrup",
    unit: "60ml 144's/box",
    stock: 0,
    description: "Herbal Supplement",
  },
  {
    name: "Multivitamins Syrup",
    unit: "60ml 144's/box",
    stock: 0,
    description: "Multivitamin",
  },
  {
    name: "Paracetamol 250mg/5ml Syrup",
    unit: "60ml 144's/box",
    stock: 0,
    description: "Analgesic",
  },
  {
    name: "Salbutamol 2mg Syrup",
    unit: "60ml 144's/box",
    stock: 0,
    description: "Bronchodilator",
  },
  {
    name: "Amoxicillin 100mg/ml Drops",
    unit: "10ml 144's/box",
    stock: 0,
    description: "Antibiotic",
  },
  {
    name: "Cetirizine 2.5mg/ml Drops",
    unit: "10ml 144's/box",
    stock: 0,
    description: "Antihistamine",
  },
  {
    name: "Multivitamins Drops",
    unit: "15ml 144's/box",
    stock: 0,
    description: "Multivitamin",
  },
  {
    name: "Paracetamol 100mg/ml Drops",
    unit: "10ml 144's/box",
    stock: 0,
    description: "Analgesic",
  },
];
